server.port=9090
client_url=${client_url}

#DB
spring.sql.init.platform=postgres
spring.sql.init.mode=always

spring.datasource.url=${connection_link_db}
spring.datasource.username=${username_db}
spring.datasource.password=${password_db}




spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.defer-datasource-initialization=true
logging.level.org.springframework.transaction.interceptor=TRACE


#OpenAI
spring.ai.openai.api-key=${openAI_key}
spring.ai.openai.embedding.options.model = text-embedding-ada-002


#OAuth2
google.clientId=${google_client_id}

#JWT
jwt.secret-key=${jwt_secret_key}


# AWS S3 Configuration
aws.s3.user-bucket=${aws_s3_user_bucket_name}
aws.s3.event-bucket=${aws_s3_event_bucket_name}
aws.s3.region=${aws_region}
aws.s3.access-key=${aws_access_key}
aws.s3.secret-key=${aws_secret_key}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Email (JavaMailSender) configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${email_cfg_email}
spring.mail.password=${email_cfg_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true